CREATE DATABASE DB_BeMyLead
GO
USE DB_BeMyLead
GO
IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'Tb_Lead') )
BEGIN
	CREATE TABLE Tb_Lead (
		ID INT IDENTITY (1, 1),
		Name NVARCHAR(50) NOT NULL,
		Email NVARCHAR(100) NOT NULL,
		PhoneNumber NVARCHAR(50) NOT NULL,
		WantsToReceiveAnnounces BIT NOT NULL,	
		PrivacyPolicy BIT NOT NULL,
		CreationDate DATETIME NOT NULL,
		LastUpdatedDate DATETIME NULL
	
		CONSTRAINT PK_Tb_Lead PRIMARY KEY (ID)
	)
END
ELSE
BEGIN
	PRINT 'Tabela já existe!';
END
